name: Run Intelligence Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Intelligence Pipeline
        run: |
          python cpid.py run all

      - name: Upload Metrics and Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: intelligence-results
          path: |
            metrics/
            logs/
